### PR TITLE
updated to sdkbase2 and patched CheckJob() "Bad Status Line" bug

### PR DESCRIPTION
**Pull request by dcchivian**

### CODE REVIEW

**Comment by dcchivian** [comment]
passing unit tests

**Comment by dcchivian** [comment]
@bio-boris do you have PR merge perms?

**Comment by bio-boris** [comment]
No

**Comment by dcchivian** [comment]
@sychan the PR was reviewed and passed by @bio-boris.  Does the process permit me to self-merge after passing review?

**Pull request merged**
